### ISSUE TITLE
API predictmatch doesnt return match history between the 2 players

### ISSUE THREAD

**Issue by Helza** [TheBB/aligulac#256]
I would have expected to receive the match history between the 2 players when i used the predictmatch api call, but it didnt receive it. (it was on the webpage)   
i'm also unable to find api call that allows me to retreive this information

**Comment by Prillan** [comment]
Sorry about the super late answer.

You can get the match history by doing the following:
Let's say that the players' ids are `id1` and `id2`, then the command is

    /api/v1/match/?apikey=KEY&pla__in=id1,id2&plb__in=id1,id2

I'll add this example to the API documentation page.
