### ISSUE TITLE
Database restore script?

### ISSUE THREAD

**Issue by jknowles** [TheBB/aligulac#290]
Hi,

I'm a new developer and trying to get a local copy of this repository working to try to contribute to the project. I'm getting stuck restoring the PostgreSQL dump file on my local machine. 

Is there a script or documentation I could be pointed to so I can get that up and running? 

This is a really cool project and I'm impressed at all the hard work here.

**Comment by TheBB** [comment]
Hi,

Where are you getting stuck? Any error message?

It should be fairly simple. Install PostgreSQL, create a database (name 
it aligulac, for example), then in the shell, as a user with R+W access 
to the aligulac database, you can run:

psql -d aligulac < dump.sql

And it should work.

Eivind

**Comment by jknowles** [comment]
Thanks for writing back. 

I keep getting stuck with this error:

````
ERROR: relation "auth_user" does not exist
REVOKE
ERROR: role "aligulac" does not exist
ERROR: role "aligulac" does not exist
REVOKE
ERROR: role "aligulac" does not exist
ERROR: role "aligulac" does not exist
REVOKE
````

I am trying to pipe this into a Postgresql docker container using this command:

````
cat aligulac.sql | docker exec -i aligulac psql -d aligulac -U postgres
````
I have tried with two different users -- postgres and an admin user. What might be the cause here?

**Comment by TheBB** [comment]
Yeah, you get the error about the aligulac role if your user isn't called aligulac, but the data should still be there.

**Comment by TheBB** [comment]
The error about auth_user is just from trying to apply a foreign key constraint to a table that isn't part of the dump. It shouldn't be problematic.

**Comment by jknowles** [comment]
Thank you! 

The error made me think something was wrong, but just tested and the data works fine now. Thanks for helping a newbie out.
