### ISSUE TITLE
Site Stability Issues?

### ISSUE THREAD

**Issue by feardragon64** [TheBB/aligulac#298]
Hello! I'm an extremely frequent user of the site and deeply appreciate the value it provides. It is also probably the number one resource for commentators researching players for a tournament and almost every single commentator uses the site.

I have noticed a lot of stability issues with the site over the past few weeks(possibly months). At times it's simply slow responses to requests(both on the website as well as on the API) and at worst requests entirely time out and the site is inaccessible due to 504 Gateway Time-outs. An example is a request I just made at 6:57pm PST on February 20th(giving specific time example in case that's useful in logs).
![image](https://user-images.githubusercontent.com/5440869/53140437-7dba0480-3541-11e9-84c0-e0ad2876851f.png)

Is this something that might be addressed? I know performance/stability issues can be sometimes hard to dig into but would love to know if it's a known issue or something still being/yet to be investigated.

Thanks so much!

**Comment by TheBB** [comment]
Yes, you're right. The site is suffering a bit, mostly because it's quite CPU intensive to run. I suspect the timeouts are mostly due to time consuming pages, either because you're asking for one or because someone else is. It could use some love but I haven't really had the time (and, to be honest, the interest) to work regularly on Aligulac for a few years now.

I'd be happy to accept help from interested and capable parties.

**Comment by tweakimp** [comment]
Can you point us to the time consuming parts of the page?
What exactly is slow?

**Comment by TheBB** [comment]
Sorry, it's kinda hard for me since it's been so long since I've worked on it.

Some database hits are poorly optimized. Either from our side or from PostgreSQL. I'm looking at htop now and there's a few select statements that have been running for about 8 CPU seconds at like 5%. That's obviously too long. I'm not sure what query it is though.

Some of the records pages regularly produce gateway timeouts. Especially http://aligulac.com/records/history/ which is one I'm trying now.

Another thing to look at is the `recompute.py` script, which runs daily and takes a couple of hours at least.

**Comment by feardragon64** [comment]
Absolutely!

The two endpoints I have noticed are either very slow or very frequently 502 are these(I notice this also when not using the API and just using the web application itself):
-Player search (`http://aligulac.com/search/json/?q=<PLAYER_NAME>`)
-Player profile (`http://aligulac.com/api/v1/player/<PLAYER_ID>/`)

It sounds like TheBB has an understanding of the issues since I've only been a consumer for the website and the API. I'll mention that even when setting timeouts to 60 seconds I still frequently encounter them. If there's anything I can do to provide more info on the problems I'm seeing let me know.

**Comment by fededevi** [comment]
Myabe a very simple fix could be to increase the cache max age/expire time. It seems it is 60 second now but it should be fine even with much higher values up to an hour?

**Comment by 0BuRner** [comment]
@TheBB do you have a few minutes to activate the "slow query log" on the server and let it run for some days then share the logs here so the community can more easily check for queries optimizations ?
Here are the steps : https://www.cybertec-postgresql.com/en/3-ways-to-detect-slow-queries-in-postgresql/

> In a default configuration the slow query log is not active. Therefore it is necessary to turn it on. You have version choices: If you want to turn the slow query log on globally, you can change postgresql.conf:
`log_min_duration_statement = 5000`
> If you set log_min_duration_statement in postgresql.conf to 5000, PostgreSQL will consider queries, which take longer than 5 seconds to be slow queries and send them to the logfile. If you change this line in postgresql.conf there is no need for a server restart. A “reload” will be enough:
`postgres=#` SELECT pg_reload_conf();`
> You can do that using an init script or simply by calling the SQL function shown above.

**Comment by TheBB** [comment]
@0BuRner Thanks for the tip. I've turned it on now. I'll let you know in a few days.

**Comment by 0BuRner** [comment]
Hey, any news? =)

**Comment by TheBB** [comment]
Yes of course, sorry.

https://gist.github.com/TheBB/f7a98a03990cb42987fa0f8c4c8935fe

This should do for a while I guess. There's a draft branch at https://github.com/TheBB/aligulac/pull/301 which should work with a newer Django.

**Comment by 0BuRner** [comment]
Thanks !
By reviewing the log file, it's pretty clear that the following request is THE request that slow the whole thing:
`2019-06-16 16:45:53 UTC [25267-1] aligulac@aligulac LOG:  duration: 34755.802 ms  statement: SELECT (rating+rating_vp) AS "tot_vp", (rating+rating_vz) AS "tot_vz", (rating+rating_vt) AS "tot_vt", "rating"."id", "rating"."period_id", "rating"."player_id", "rating"."prev_id", "rating"."rating", "rating"."rating_vp", "rating"."rating_vt", "rating"."rating_vz", "rating"."dev", "rating"."dev_vp", "rating"."dev_vt", "rating"."dev_vz", "rating"."comp_rat", "rating"."comp_rat_vp", "rating"."comp_rat_vt", "rating"."comp_rat_vz", "rating"."bf_rating", "rating"."bf_rating_vp", "rating"."bf_rating_vt", "rating"."bf_rating_vz", "rating"."bf_dev", "rating"."bf_dev_vp", "rating"."bf_dev_vt", "rating"."bf_dev_vz", "rating"."position", "rating"."position_vp", "rating"."position_vt", "rating"."position_vz", "rating"."decay", "rating"."domination", "period"."id", "period"."start", "period"."end", "period"."computed", "period"."needs_recompute", "period"."num_retplayers", "period"."num_newplayers", "period"."num_games", "period"."dom_p", "period"."dom_t", "period"."dom_z", "player"."id", "player"."tag", "player"."name", "player"."romanized_name", "player"."birthday", "player"."mcnum", "player"."tlpd_id", "player"."tlpd_db", "player"."lp_name", "player"."sc2e_id", "player"."country", "player"."race", "player"."current_rating_id", "player"."dom_val", "player"."dom_start_id", "player"."dom_end_id" FROM "rating" INNER JOIN "period" ON ( "rating"."period_id" = "period"."id" ) INNER JOIN "player" ON ( "rating"."player_id" = "player"."id" ) WHERE ("rating"."decay" < 4 AND "rating"."period_id" > 16) ORDER BY "rating"."rating" DESC LIMIT 200
`

Can you execute that request prefixed with "EXPLAIN ANALYZE" and give us the result ? It will run it to show the processed time for every stage of the request.

**Comment by TheBB** [comment]
Sorry for the delay. I added it to the original gist, here: https://gist.githubusercontent.com/TheBB/f7a98a03990cb42987fa0f8c4c8935fe/raw/668f058a974df7d15fde1d24755d5c10d492ecb7/gistfile2.txt

I'm not experienced in reading these but I'm guessing the fact that it feels the need to "seq scan" the rating table (which is huge) is the problem.

**Comment by feardragon64** [comment]
I just want to add that the past week and a half the site has been incredibly stable. There's no commits to the repo on master so I don't know if anything has actually been done but I just wanted to remark on it.

**Comment by TheBB** [comment]
There was a pending free upgrade on Linode that I pulled the trigger on. That was more like a month ago though, but I'm guessing it's related.

**Comment by 0BuRner** [comment]
Great, thank you @TheBB we are close to the solution :p
It is indeed not an easy to read report, but with that website, it's a bit clearer : https://explain.depesz.com/s/twav (seems we can get more info with ```EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON)``` and this tool : http://tatiyants.com/pev/#/plans/new)
As we can see, the main problem seems there are missing indexes which are leading to "seq scan" that takes huge amount of time 33s out of the 34s...
Can you add an multi-columns index on table rating for columns ."decay" and "period_id" ?
Should be : `CREATE INDEX rating_period_decay ON rating(decay, period_id);` ? The best thing to do right after that is to reexecute the EXPLAIN (ANALYZE, BUFFERS) on the query to see if the optimization when right.

**Comment by 0BuRner** [comment]
Add another index on "rating.rating" for better optimization.

**Comment by TheBB** [comment]
Aye, that's magical. https://gist.githubusercontent.com/TheBB/f7a98a03990cb42987fa0f8c4c8935fe/raw/c1e399196874262595ba52e99411660dc0165b61/gistfile2.txt

Thanks for the help @0BuRner. I'll leave this open for a while more and see if I can catch some others.

**Comment by 0BuRner** [comment]
Hello,
I haven't faced performance issue since then, did you?
I think you can check the performance logs a last time and if everything seems OK, disable it :)
