### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by Die4Ever** [TheBB/aligulac#332]
it's dead :(

**Comment by Die4Ever** [comment]
wait sorry I had https on it, works on http

**Comment by TheBB** [comment]
Yeah, it's embarassing. I should really get it working on HTTPS.

**Comment by Die4Ever** [comment]
> Yeah, it's embarassing. I should really get it working on HTTPS.

I understand your pain, I avoided it for a long time too

**Comment by 0BuRner** [comment]
You should take a look at this if setting HTTPS is a pain for you : https://certbot.eff.org/
